### ISSUE TITLE
MELBOURNE_SPEC_VERSION behavior

### ISSUE THREAD

**Issue by southerngs** [rubinius/rubinius-melbourne#13]
The [Travis CI build](https://travis-ci.org/rubinius/rubinius-melbourne/jobs/22334633) is currently failing. With the following errors:

`````
extconf.rb:21:in `+': no implicit conversion of Fixnum into String (TypeError)
	from extconf.rb:21:in `block (2 levels) in <main>'
	from extconf.rb:21:in `map'
	from extconf.rb:21:in `block in <main>'
	from extconf.rb:16:in `open'
	from extconf.rb:16:in `<main>'
rake aborted!
`````

That corresponds with the code:

``````
if ENV["MELBOURNE_SPEC_VERSION"]
    # Alter the version to not match any possible loaded version
    version = version.split(".").map { |x| x + 1 }.join(".")
  end
``````

The error could be fixed by changing the code to ` |x| x.to_i + 1`, but I don't know what the intent of this is.  For example the current version is `2.1.0.0`.  It looks to me like this code is trying to increment all the version numbers so it would go to `3.2.1.1`.  But I don't know why that would be the desired behavior.

**Comment by brixen** [comment]
This was removed. This repo is being deleted. See https://github.com/rubinius/rubinius-code.
